name = "puzzle"
type = "webpack"

account_id = "bc068512994d36dd85f41c4c0b27c489"
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2021-11-14"

kv_namespaces = [
    { binding = "KV_PUZZLE", preview_id = "b661362d37814bd5bd3c84c049b737a1", id = "d8da34f3cfb7418785a1d24e0c1594c6" },
    { binding = "KV_PUZZLE_THROTTLE", id = "bfecccdc7e6342bbb04373272f67e734" }
]